### ISSUE TITLE
Add initial architecture design

### ISSUE THREAD

**Issue by YuriNeverov** [YuriNeverov/Tic-Tac-Toe#2]
We need to specify initial architecture design, which may be changed in the future

**Comment by YuriNeverov** [comment]
![tic-tac-toe-arch drawio](https://github.com/YuriNeverov/Tic-Tac-Toe/assets/47862299/9a6e401a-3df6-4965-adf1-3f25d2191c62)

**Comment by YuriNeverov** [comment]
First estimation of architectural design is available in the comment above.
@RazO0m, please, take a look

**Comment by RazO0m** [comment]
Cool! Looks interesting
